routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::redirect('/', 'login');
Route::middleware(['auth'])->group(function () {
    Route::get('dashboard', [\App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
    Route::post('/dashboard/application/check', [\App\Http\Controllers\DashboardController::class, 'checkApplication'])->name('dashboard.application.check');
//    Route::get('/getFilteredData/{academyId}', [\App\Http\Controllers\DashboardController::class, 'getFilteredData']);
//    Route::get('/projects', [\App\Http\Controllers\DashboardController::class, 'getPaginatedProjects'])->name('dashboard.paginated');
    Route::resource('profile', ProfileController::class);
    Route::resource('project', \App\Http\Controllers\ProjectController::class);
    Route::resource('application', \App\Http\Controllers\ApplicationController::class);
});


require __DIR__ . '/auth.php';

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'assembled',
        'name',
        'description',
    ];

    public function profiles(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Academy::class);
    }

    public function user(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function applications(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Application::class);
    }

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreProjectRequest;
use App\Http\Requests\UpdateProjectRequest;
use App\Models\Academy;
use App\Models\Project;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        return view('project.index', [
            'projects' => Project::where('user_id', Auth::id())->latest()->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $academies = Academy::all();
        return \view('project.create', compact('academies'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreProjectRequest $request): \Illuminate\Http\RedirectResponse
    {

        $project = Project::create([
            'user_id' => Auth::id(),
            'name' => $request->name,
            'description' => $request->description,
            'academy_id' => $request->academy_id,
        ]);
        $project->profiles()->sync($request->academy);

        return redirect()->route('project.index')->with(['message' => 'Project successfully created']);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Project $project): View
    {
        return view('project.edit', [
            'project' => $project,
            'academies' => Academy::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateProjectRequest $request, Project $project)
    {
        $project->user_id = Auth::id();
        $project->name = $request->name;
        $project->description = $request->description;

        $project->save();

        $project->profiles()->sync($request->academy);

        return to_route('project.index')->with(['message' => 'Project successfully updated']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Project $project): RedirectResponse
    {
        $project->profiles()->detach($project->profiles);
        $project->applications()->delete();
        $project->delete();

        return to_route('project.index')->with(['message' => 'Project successfully deleted']);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/project/create.blade.php
@extends('layouts.guest')
@section('class', 'background-profile')
<x-app-layout xmlns="http://www.w3.org/1999/html">
    <div class="container">
        <h1 class="font-semibold text-left px-5 overflow-hidden shadow-sm sm:rounded-lg text-xl">New Project !</h1>
    </div>
    <form action="{{ route('project.store') }}" method="POST">
        @csrf
        @method('POST')
        <div class="px-2 py-5">
            <div class="flex -mx-2">
                <div class="w-1/2 px-2">
                    <div class="grid md:grid-cols-2 md:gap-6">
                        <div class="relative z-0 w-full mb-6 group">
                            <div class="relative z-0 w-full mb-1 group">
                                <input type="text" id="name" name="name" value="{{ old('name') }}"
                                       placeholder="Name of project"
                                       autocomplete="name"
                                       class="block py-2.5 px-0 w-full text-sm text-black bg-transparent border-0 border-b-2
                                            border-gray-300 appearance-none dark:text-black dark:border-gray-600
                                            dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"/>
                                <label for="name"
                                       class="peer-focus:font-medium absolute text-sm text-black dark:text-black duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-black-600 peer-focus:dark:text-black-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"></label>
                                @error('name')
                                <div class="text-red small">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="relative z-0 w-full mb-1 group">
                                <textarea class="block py-2.5 px-0 w-full text-sm text-black bg-transparent border-0 border-b-2
                                border-gray-300 appearance-none dark:text-black dark:border-gray-600
                                dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                                          placeholder="Description of project" id="description" name="description"
                                          style="height: 220px; resize:none;">{{ old('description') }}</textarea>
                                <label for="description" :value="__('Description')"
                                       class="peer-focus:font-medium absolute text-sm text-black dark:text-black duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-black-600 peer-focus:dark:text-black-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"></label>
                                @error('description')
                                <div class="text-red small">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
                <div class="w-2/4 px-2">
                    <h1 class="font-semibold text-left px-5 text-xl">What i need</h1>
                    <div class="inline-flex items-center">
                        <div class="grid grid-cols-4 gap-4">
                            @foreach ($academies as $academy)
                                <input type="checkbox" class="form-check-input" name="academy[]"
                                       value="{{ $academy->id }}"
                                       id="academy{{ $academy->id }}">
                                <label for="academy{{ $academy->id }}"
                                       class="form-check-box card-square rounded-lg font-semibold shadow-sm small border rounded-2 m-1">
                                    {{ $academy->name }}
                                </label>
                            @endforeach
                        </div>
                    </div>
                    @error('$academy')
                    <div class="text-red small">{{ $message }}</div>
                    @enderror
                </div>
            </div>
        </div>
        <div class="px-5">
            <button type="submit"
                    class="text-white color-green font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none">
                CREATE
            </button>
            <a href="{{ route('project.index') }}" class="text-sm font-semibold">Back</a>
        </div>
    </form>
    @section('scripts')
        <script>
            $(function () {
                $('input[type="checkbox"]').on('click', function () {
                    let academySelect = $(this).val();
                    let label = $(`label[for="academy${academySelect}"]`);

                    if ($(this).is(':checked')) {
                        label.addClass('bg-green text-white selected');
                    } else {
                        label.removeClass('bg-green text-white selected');
                    }
                });
            });
        </script>
    @endsection
</x-app-layout>

resources/views/project/edit.blade.php
@extends('layouts.guest')
@section('class', 'background-profile')
<x-app-layout xmlns="http://www.w3.org/1999/html">
    <div class="container">
        <h1 class="font-semibold text-left px-5 overflow-hidden shadow-sm sm:rounded-lg text-xl">New Project !</h1>
    </div>
    <form action="{{ route('project.update', $project->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="px-2 py-5">
            <div class="flex -mx-2">
                <div class="w-1/2 px-2">
                    <div class="grid md:grid-cols-2 md:gap-6">
                        <div class="relative z-0 w-full mb-6 group">
                            <div class="relative z-0 w-full mb-1 group">
                                <input type="text" id="name" name="name" value="{{ $project->name }}"
                                       placeholder="Name of project"
                                       autocomplete="name"
                                       class="block py-2.5 px-0 w-full text-sm text-black bg-transparent border-0 border-b-2
                                            border-gray-300 appearance-none dark:text-black dark:border-gray-600
                                            dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"/>
                                <label for="name"
                                       class="peer-focus:font-medium absolute text-sm text-black dark:text-black duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-black-600 peer-focus:dark:text-black-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"></label>
                                @error('name')
                                <div class="text-red small">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="relative z-0 w-full mb-1 group">
                                <textarea class="block py-2.5 px-0 w-full text-sm text-black bg-transparent border-0 border-b-2
                                border-gray-300 appearance-none dark:text-black dark:border-gray-600
                                dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                                          placeholder="Description of project" id="description" name="description"
                                          :value="{{ old('description') }}"
                                          style="height: 220px; resize:none;">{{ $project->description }}</textarea>
                                <label for="description" :value="__('Description')"
                                       class="peer-focus:font-medium absolute text-sm text-black dark:text-black duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-black-600 peer-focus:dark:text-black-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"></label>
                                @error('description')
                                <div class="text-red small">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
                <div class="w-2/4 px-2">
                    <h1 class="font-semibold text-left px-5 text-xl">What i need</h1>
                    <div class="inline-flex items-center">
                        <div class="grid grid-cols-4 gap-4">
                            @php
                                $projectAcademyIds = $project->profiles->pluck('id')->toArray();
                            @endphp

                            @foreach ($academies as $academy)
                                <input type="checkbox" class="form-check-input" name="academy[]"
                                       value="{{ $academy->id }}"
                                       id="academy{{ $academy->id }}" {{ (in_array($academy->id, $projectAcademyIds)) ? 'checked' : '' }}>
                                <label for="academy{{ $academy->id }}" id="academy{{ $academy->id }}"
                                       class="form-check-box card-square rounded-lg font-semibold shadow-sm small border rounded-2 m-1 {{ (in_array($academy->id, $projectAcademyIds)) ? 'bg-green text-white' : 'bg-light' }}">
                                    {{ $academy->name }}
                                </label>
                            @endforeach
                        </div>
                    </div>
                    @error('$academy')
                    <div class="text-red small">{{ $message }}</div>
                    @enderror
                </div>
            </div>
        </div>
        <div class="px-5">
            <button type="submit"
                    class="text-white color-green font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none">
                UPDATE
            </button>
            <a href="{{ route('project.index') }}" class="text-sm font-semibold">Back</a>
        </div>
    </form>
    @section('scripts')
        <script>
            $(function () {
                $('input[type="checkbox"]').on('click', function () {
                    let academySelect = $(this).val();
                    let label = $(`label[for="academy${academySelect}"]`);

                    if ($(this).is(':checked')) {
                        label.addClass('bg-green text-white selected');
                    } else {
                        label.removeClass('bg-green text-white selected');
                    }
                });
            });
        </script>
    @endsection
</x-app-layout>

resources/views/project/index.blade.php
@extends('layouts.guest')
@section('class', 'background-profile')
<x-app-layout xmlns="http://www.w3.org/1999/html">
    @if(\Illuminate\Support\Facades\Auth::user()->is_edited == 1)
        <div class="flex flex-col sm:flex-row justify-center sm:justify-between items-center">
            <div class="py-12">
                <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 grid-cols-12">
                    <p class="font-semibold mb-0">Have a new idea to make the world better?</p>
                    <a href="{{ route('project.create') }}" class="text-xl font-semibold">Create new project
                        <img src="{{ asset('/icons/1.png') }}" width="30" height="30" alt="..."
                             style="display: inline-block">
                    </a>
                </div>
            </div>
        </div>
        @foreach($projects as $project)
            @if ($project->assembled == 0)
                <a href="{{ route('project.edit', $project->id) }}" class="absolute project-icon">
                    <img src="{{ asset('/icons/8.png') }}" width="30" height="30" alt="...">
                </a>
                <form action="{{ route('project.destroy', $project->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="project-icon" style="border: none; background: none;">
                        <img src="{{ asset('/icons/7.png') }}" width="30" height="30" alt="Delete">
                    </button>
                </form>
            @endif
            <div class="flex justify-center items-center py-5">
                <div class="max-w-4xl mx-auto p-4">
                    <div class="flex justify-between bg-white rounded-lg">
                        <div class="p-8">
                            <img src="{{ \Illuminate\Support\Facades\Auth::user()->Avatar() }}"
                                 class="absolute card-image rounded-full shadow-sm" width="100"
                                 height="100" alt="...">
                            <p class="font-semibold text-sm">{{ $project->user->name }} {{ $project->user->surname }}</p>
                            <p class="font-semibold text-sm text-orange-500">
                                {{--                                {{ $project->user->academy_id }}--}}
                                /
                            </p>
                            <div class="object-left-bottom pt-10">
                                <p class="font-semibold text-xs">I'm looking for...</p>
                                <div class="flex">
                                    @foreach ($project->profiles as $choose)
                                        <div
                                            class="border-card-options absolute text-xs mx-1 color-green text-white shadow-sm rounded-full p-1 flex-column align-items-center justify-content-center text-center">
                                            {{ $choose->display_name }}
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                        <div class="p-8">
                            <p class="font-semibold">{{ $project->name }}</p>
                            @if (strlen($project->description) > 120)
                                <span
                                    id="short_bio{{ $project->id }}">{{ Str::limit($project->description, 120) }}</span>
                                <span id="long_bio{{ $project->id }}"
                                      style="display: none;">{{ $project->description }}</span>
                                <a id="show_more{{ $project->id }}" data-id="{{ $project->id }}" href="#"
                                   class="text-orange-500 small text-end">show more</a>
                                <a class="text-orange-500 small text-end" id="show_less{{ $project->id }}"
                                   data-id="{{ $project->id }}" href="#"
                                   style="display: none;">Show Less</a>
                            @else
                                {{ $project->description }}
                            @endif
                            @if ($project->assembled)
                                <div
                                    class="absolute card-circle color-green text-white text-decoration-none pointer font-semibold">
                                    {{ $project->applications->count() }}<br>Applicants
                                </div>
                            @else
                                <a href="{{  route('application.show', $project->id) }}"
                                   class="absolute card-circle color-green text-white text-decoration-none pointer font-semibold">
                                    {{ $project->applications->count() }}<br>Applicants</a>
                            @endif
                            @if ($project->assembled)
                                <img src="{{ asset('/icons/badge.png') }}" class="" width="40"
                                     height="40"
                                     alt="...">
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    @else
        <p class="font-semibold mb-0">Please edit your profile so you can use our futures</p>
    @endif
    @section('scripts')
        <script>
            $(function () {
                $('a.options').on('click', function (e) {
                    e.preventDefault()
                    this.closest('form').submit()
                });
                $('body').on('click', `a[id^='show_more']`, function (e) {
                    e.preventDefault();

                    let id = $(this).attr('data-id');

                    $(`#short_bio${id}`).fadeOut();
                    $(`#long_bio${id}`).fadeIn();
                    $(`#show_more${id}`).hide();
                    $(`#show_less${id}`).show();
                });

                $('body').on('click', `a[id^='show_less']`, function (e) {
                    e.preventDefault();

                    let id = $(this).attr('data-id');

                    $(`#long_bio${id}`).fadeOut();
                    $(`#short_bio${id}`).fadeIn();
                    $(`#show_less${id}`).hide();
                    $(`#show_more${id}`).show();
                });
            });
        </script>
    @endsection
</x-app-layout>